---

- name: Install a list of packages
  ansible.builtin.apt:
    pkg:
      - iptables-persistent
      - keepalived      
- name: Remove dependencies that are no longer required and purge their configuration files
  ansible.builtin.apt:
    autoremove: yes
    purge: true

      
