---
hyperv:
  children:
    lb:
      hosts:
        10.10.0.25[3:4]:
    fw:
      hosts:
        10.1.0.[1:4]:
    sql:
      hosts:
        10.0.1.1:
    ansible_connection: ssh
    ansible_user: ansible
    ansible_network_os: linux
    ansible_password: ansible1234!
    ansible_become_password: ansible1234!
    ansible_ssh_pass: ansible1234!
    dns_servers:
      - 1.1.1.1
      - 1.1.1.3
      - 8.8.8.8
      - 1.1.1.1
    ntp_servers:
      - 196.10.55.57
      - 160.119.248.252
      - 196.10.54.58
      - 196.49.100.57
    
