---
- name: Update Load Balancers
  hosts: lb
  gather_facts: yes
  become: yes
  vars_files:
    - '~/cos731_fa2_project/vault.yml'  
  roles:
    - role: './roles/debiancommon'
    - role: './roles/lb'
  
        
